### ISSUE TITLE
Some Readline issue is breaking Pry / Guard

### ISSUE THREAD

**Issue by daaain** [docker-library/ruby#155]
I think since the Readline lib went from version 6 to 7 (not really sure, but I only started to experience the issue yesterday, maybe due to moving from Alpine 3.4 to 3.6 or by adding a fresher package repository) I can't use Guard at all, it's blowing up as soon as it starts with a Pry / Readline related issue (pasted below).

I spent some time trying to fix it, installing `readline-dev` package didn't help, but from what I understood people say Ruby itself needs to be rebuilt linking the new Readline.

I don't think I can rebuild Ruby unless I copy and paste the Dockerfile contents so was wondering if this is something you can look into?

Thanks!

```
16:50:59 - INFO - Guard::RSpec is running
16:51:14 - INFO - Guard is now watching at '/var/opt/alderhey-backend'
Sorry, you can't use Pry without Readline or a compatible library.
Possible solutions:
 * Rebuild Ruby with Readline support using `--with-readline`
 * Use the rb-readline gem, which is a pure-Ruby port of Readline
 * Use the pry-coolline gem, a pure-ruby alternative to Readline
/usr/local/bundle/gems/pry-0.10.4/lib/pry/config/default.rb:151:in `require': Error loading shared library libreadline.so.6: No such file or directory (needed by /usr/local/lib/ruby/2.4.0/x86_64-linux-musl/readline.so) - /usr/local/lib/ruby/2.4.0/x86_64-linux-musl/readline.so (LoadError)
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/default.rb:151:in `lazy_readline'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/default.rb:6:in `block in <class:Default>'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/default.rb:125:in `instance_eval'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/default.rb:125:in `block (2 levels) in <class:Default>'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/behavior.rb:54:in `public_send'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/config/behavior.rb:54:in `method_missing'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/history.rb:19:in `restore_default_behavior'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/history.rb:14:in `initialize'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/pry_class.rb:33:in `new'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/pry_class.rb:33:in `history'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/pry_class.rb:222:in `load_history'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/pry_class.rb:129:in `initial_session_setup'
	from /usr/local/bundle/gems/pry-0.10.4/lib/pry/pry_class.rb:154:in `start'
	from /usr/local/bundle/gems/guard-2.14.1/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
```

**Comment by daaain** [comment]
Oh actually, if I also add this line to my Dockerfile:

```
RUN ln -s /usr/lib/libreadline.so /usr/lib/libreadline.so.6
```

Then it works!

It still does sound like a linking issue though.

**Comment by tianon** [comment]
I can't seem to reproduce a failure with either Alpine version: :confused: 
```console
$ docker pull ruby:2.4-alpine3.4
2.4-alpine3.4: Pulling from library/ruby
Digest: sha256:4f8f076076f480e1ffe732e12686a9182045bc44a9de71dee51b6e76cf417bf9
Status: Image is up to date for ruby:2.4-alpine3.4

$ docker run -it --rm ruby:2.4-alpine3.4 ruby -rreadline -e 'puts Readline::VERSION'
6.3


$ docker pull ruby:2.4-alpine3.6
2.4-alpine3.6: Pulling from library/ruby
Digest: sha256:5c387781978bf303c865017d1e1e6427962951e17cab312df34b2acd21283016
Status: Image is up to date for ruby:2.4-alpine3.6

$ docker run -it --rm ruby:2.4-alpine3.6 ruby -rreadline -e 'puts Readline::VERSION'
6.3
```

**Comment by daaain** [comment]
I can confirm that after doing a `docker pull` (as you did) the problem went away, so I suspect I had an earlier image cached and didn't realise it wasn't being updated 🤦‍♂️  

Sorry for the slightly time wasting issue...
