### ISSUE TITLE
ruby:2.4.3 (2.4) bundler invalid multibyte char (UTF-8) (SyntaxError)

### ISSUE THREAD

**Issue by noelblaschke** [docker-library/ruby#180]
Hey,

running a very basic setup like:

Dockerfile:
```
FROM ruby:2.4.3 (or 2.4)
WORKDIR /
COPY Gemfile.* /
RUN bundle install

....
```

results in 

```
> docker build --no-cache .
Sending build context to Docker daemon   2.63MB
Step 1/3 : FROM ruby:2.4
 ---> 713da53688a6
Step 2/3 : COPY Gemfile* /
 ---> 4a9423ae2f9d
Step 3/3 : RUN bundle install
 ---> Running in 6008c707ee6c
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:1: invalid multibyte char (UTF-8) (SyntaxError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:10:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
The command '/bin/sh -c bundle install' returned a non-zero code: 1
```

Removing the WORKDIR & COPY instructions throws the same error.

I've already tried to install ruby 2.4.3 with bundler 1.16.1 on my local machine: It works out of the box (at least i lol'd).

Thanks in advance.

System:
MacOS High Sierra 10.13.2 
Docker Engine 17.12.0-ce-mac45 (21669)

Quick solution:
Use ruby:2.4.2, it does work fine.

**Comment by lox** [comment]
Unfortunately this is affecting me too, and on ruby:2.4.2. It seems that random files are corrupted with binary data:

```
root@a0e974544a2c:/usr/local/bundle# cat /usr/local/bundle/gems/thread_safe-0.3.6/lib/thread_safe.rb
�*�k�\���Q8!K�j��0a�����yCf(����ᙪ=��'ϣ(�O�k1�r��p�Sg��i��`�?�`9�*�%�|�����V;��p�A���ӎX�4����t	C�Sw[}�7����*�J�7��Y^
                                                                                                                      ؘK&Yh|�
���.�J�4��y:}N�����v�;0�{�1~͜�
l��~�E(1���^*��6�t�^y�����͞v��)��ŕAd_����+.09z*B�m}H3$�mk�{lw�t�CD��}���G��
                                                                          Ă�.T��6ʑ�ǋ��-�="�2K<��qU_r��|�R�q��L(��@h�I�(\3T�,(��`<ZQ;���d��ȴ֯�@÷�HQ�9�� �����0:�ս2��f��&��Xk�Q8b�IV�居�^��U�
                                                                                                                                                                                           2h�#�����c���,��Ú<	��E�g���t[D��$��Oe,|f
S(�3�$±�v+J�0�
u(^�^��=���g`�0���6<��$�j���ݷ8x���KX�ra2�fHh�͑AvF�JK*��p�4:�e4
+$d���sUi�v��֤�>G�\�q��斤����{cL)��n���TO�R�1"ƴ��{��%�P]�4|5{��Hx��X�G��a�]18�?$�*g��(�ﬞ5�����JǴ�U}��)
                                                                                                    e�*v9�h�I�&=s(�-���&�:���V�4�P
                                                                                                                                  �2^ff��6K�
�(D��`�-w�)��r`r|�
.��S�ϠڭL�5_��J�:|�V��+��� �������d5C�Q�u�\N��WV<+�T��rU��=���9$�r؀/�[EJ..s������
�\Ж�X�Qǂ��=\mr�|���_���T��/�T��X['m��6]`���PR�e��so�a��8GQ��)[^�+�L�:����ނo9�z�M��Ѝ�����\�ge�]�aw�4Wh��,�gy�:��%��CŪ��QÂ�,Z���}�}ٝ�݈����M
                                                                                                                                       ���w��=b�1=�6���F0��d-\к��x�u݇Q^�^]��
cF�f]��EO�%I�k�b���#o?_9q3���h���#�ŕ�)�Xb��Ԗ[�z�ן�O�vi�A�?���:M���9�u�p���y��r�3;;`ǭE�?�_��"[�
�'���Ս�A�#>>�܁{#��HFs���A��9�(�J�,���2���:WNQ_��7U�uC{���t�/���y��Ow���qK\��Q�&� �l�v��O�-�
                                                                                            O��|��Dj�Y�6n�X-�'u��P:�E�
```

This can be fixed with `gem pristine ...`. 

I'm on MacOS High Sierra 10.13.2 and Version 17.12.0-ce-mac49 (21995).

**Comment by lox** [comment]
My money is on this being a Docker for Mac issue, something something layering?

**Comment by lox** [comment]
Looks to me like this is related to https://github.com/docker/for-mac/issues/2327#issuecomment-351842252.

**Comment by deivid-rodriguez** [comment]
This is a common problem in docker images because they don't set the default locale to UTF-8 (see for example https://github.com/docker-library/ruby/issues/45 or https://github.com/docker-library/ruby/pull/64). It happens in this situation when a gemspec with a non-utf8 character is read.

Both the fix for the crash (https://github.com/bundler/bundler/pull/6279) and the fix to give a better error message (https://github.com/bundler/bundler/pull/6254) have landed to bundler, but have not been released yet.

**Comment by lox** [comment]
I was seeing arbitrary ruby files filled with garbled binary data. It was fixed for me by reverting to a qcow docker for mac VM format.

**Comment by tianon** [comment]
Yeah, we've been seeing a lot of those recently -- see https://github.com/docker/for-mac/issues/2327. :disappointed:

**Comment by yosifkit** [comment]
Closing since this is an issue with Docker for Mac and not an issue with the image.
