### ISSUE TITLE
bundle install fails on ruby:2.4.4-alpine3.7 when gems have native extensions

### ISSUE THREAD

**Issue by unikitty37** [docker-library/ruby#221]
When I try running `bundle install` on a Docker image derived from `ruby:2.4.4-alpine3.7`, it fails when it reaches a gem that has native extensions (for example, Nokogiri).

Indeed, if I run `docker run -it ruby:2.4.4-alpine3.7 sh` and type `make`, I get `sh: make: not found`.

Would it be possible for the images to include the necessary build tools? (And, as a short-term fix, could somebody please tell me the Alpine equivalent of Ubuntu's `build-essentials` package so I can get GitLab's CI set up and working? :)

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/builds/project/test-project/cache/ruby/2.4.0/gems/nokogiri-1.8.2/ext/nokogiri
/usr/local/bin/ruby -r ./siteconf20180621-14-1p1kra6.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'
```

**Comment by Nakilon** [comment]
I'm surprised that Alpine does not have any package with Ruby source code attached.
https://pkgs.alpinelinux.org/contents?file=bignum.c&path=&name=&branch=edge
What am I supposed to do to compile a gem that uses such file? Should I discard using the official Ruby Docker images in favour of rbenv or should I do a git clone a tag of Ruby repo?

**Comment by tianon** [comment]
This isn't really a great place to discuss it (the forums or some other dedicated support channel would probably be better), but it would probably help if you gave an example of such a gem so we could try to reproduce?
