### ISSUE TITLE
libcurl disappeared alpine3.13

### ISSUE THREAD

**Issue by Kasvit** [docker-library/ruby#345]
Hello
After build  image, it can't filnd libcurl
my Docfile
```
FROM ruby:2.6.6-alpine3.13 as Builder
WORKDIR /usr/src/app

RUN apk add --no-cache openssh git build-base gcc mysql-dev nodejs tzdata \
  mysql-client mariadb-connector-c openssl-dev nodejs \
  curl wget libcurl libressl-dev curl-dev libxml2 libxslt libstdc++ libxml2-dev libxslt-dev libffi-dev curl-dev

COPY Gemfile* ./

RUN gem install bundler -v 2.0.2

RUN bundle config --global frozen 1 \
 && bundle install -j4 --retry 3 --without development test \
 # Remove unneeded files (cached *.gem, *.o, *.c)
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /usr/local/bundle/gems/ -name "*.c" -delete \
 && find /usr/local/bundle/gems/ -name "*.o" -delete

FROM ruby:2.6.6-alpine3.13
WORKDIR /usr/src/app
COPY --from=Builder /usr/local/bundle/ /usr/local/bundle/
COPY . .

ENV LANG C.UTF-8
ENV RACK_ENV production

EXPOSE 3000

ENTRYPOINT ["bundle", "exec"]
CMD ["puma", "-C", "config/puma.rb"]

```
And when I run it
```
Puma starting in single mode...
* Version 3.11.4 (ruby 2.6.6-p146), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: production
LoadError: Could not open library 'libcurl': Error loading shared library libcurl: No such file or directory.
Could not open library 'libcurl.so': Error loading shared library libcurl.so: No such file or directory.
Could not open library 'libcurl.so.4': Error loading shared library libcurl.so.4: No such file or directory
  /usr/local/bundle/gems/ffi-1.12.2/lib/ffi/library.rb:145:in `block in ffi_lib'
  /usr/local/bundle/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `map'
  /usr/local/bundle/gems/ffi-1.12.2/lib/ffi/library.rb:99:in `ffi_lib'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `require'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon.rb:15:in `require'
  /usr/local/bundle/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
  /usr/local/bundle/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `require'
  /usr/local/bundle/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
  /usr/src/app/app/app.rb:11:in `require'
  /usr/src/app/app/app.rb:11:in `<top (required)>'
  config.ru:2:in `require'
  config.ru:2:in `block in <main>'
  /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/configuration.rb:318:in `load_rackup'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/configuration.rb:243:in `app'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/runner.rb:138:in `load_and_bind'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/single.rb:87:in `run'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
  /usr/local/bundle/gems/puma-3.11.4/lib/puma/cli.rb:78:in `run'
  /usr/local/bundle/gems/puma-3.11.4/bin/puma:10:in `<top (required)>'
  /usr/local/bundle/bin/puma:23:in `load'
  /usr/local/bundle/bin/puma:23:in `<top (required)>'
! Unable to load application: LoadError: Could not open library 'libcurl': Error loading shared library libcurl: No such file or directory.
Could not open library 'libcurl.so': Error loading shared library libcurl.so: No such file or directory.
Could not open library 'libcurl.so.4': Error loading shared library libcurl.so.4: No such file or directory
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)

```

**Comment by Kasvit** [comment]
Full filx
```
FROM ruby:2.6.6-alpine3.13 as Builder
WORKDIR /usr/src/app


RUN apk add --no-cache openssh git build-base gcc mysql-dev nodejs

COPY Gemfile* ./

RUN gem install bundler -v 2.0.2

RUN bundle config --global frozen 1 \
 && bundle install -j4 --retry 3 --without development test \
 # Remove unneeded files (cached *.gem, *.o, *.c)
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /usr/local/bundle/gems/ -name "*.c" -delete \
 && find /usr/local/bundle/gems/ -name "*.o" -delete

FROM ruby:2.6.6-alpine3.13

WORKDIR /usr/src/app
COPY --from=Builder /usr/local/bundle/ /usr/local/bundle/
COPY . .

ENV LANG C.UTF-8
ENV RACK_ENV production

 >>>>>>>>>>>>>>> moved here
RUN apk add --no-cache mysql-client mariadb-connector-c openssl-dev nodejs \
  curl wget libstdc++ libffi-dev libc-dev linux-headers \
  libxml2-dev libxslt-dev libgcrypt-dev

EXPOSE 3000

ENTRYPOINT ["bundle", "exec"]
CMD ["puma", "-C", "config/puma.rb"]

```
