### ISSUE TITLE
Unexpected behaviour of File.executable? for ruby 3 on different versions of Alpine

### ISSUE THREAD

**Issue by jmlagace** [docker-library/ruby#372]
After trying to figure out why my Rails application would not run on the server when it was behaving perfectly fine on my development machine I narrowed the problem to a combination of ruby version with alpine versions. 

Somehow the method File.executable? does not detect executable binaries on specific versions of the ruby/alpine images.

I tested on Docker Desktop 4.2 with Docker 20.10.8 on OSX Big Sur (11.2) and Docker 19.03.2 on Ubuntu 18.04.3

I would expect all commands to return yes since the ruby code is testing if the ruby binary is executable. The code is puts File.executable?(‘/usr/local/bin/ruby’)

The command utilized to demonstrate the problem is (it loops through multiple versions of the images):
```
images=( "ruby:3.0.3-alpine3.15" "ruby:3.0.3-alpine3.14" "ruby:3.0.3-alpine3.13" "ruby:3.0.2-alpine3.14" "ruby:3.0.2-alpine3.13" "ruby:3.0.1-alpine3.13" )
for image in "${images[@]}"
do
  sudo docker pull $image
done
for image in "${images[@]}"
do
	echo "testing with " $image " result is " $(sudo docker run --rm -it $image ruby -e "puts File.executable?('/usr/local/bin/ruby')")
done
```

The result SHOULD BE:
```
testing with ruby:3.0.3-alpine3.15 result is true
testing with ruby:3.0.3-alpine3.14 result is true
testing with ruby:3.0.3-alpine3.13 result is true
testing with ruby:3.0.2-alpine3.14 result is true
testing with ruby:3.0.2-alpine3.13 result is true
testing with ruby:3.0.1-alpine3.13 result is true

```
On my Ubuntu server it is:
```
testing with ruby:3.0.3-alpine3.15 result is false
testing with ruby:3.0.3-alpine3.14 result is false
testing with ruby:3.0.3-alpine3.13 result is true
testing with ruby:3.0.2-alpine3.14 result is false
testing with ruby:3.0.2-alpine3.13 result is true
testing with ruby:3.0.1-alpine3.13 result is true

```

**Comment by tianon** [comment]
Interesting -- it could possibly be related to https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Comment by yosifkit** [comment]
If that is what is causing the problem, then the solution is to update Docker and `libseccomp` on the Ubuntu host.

> Docker 20.10.0 (which contains moby commit a181391) or greater, AND libseccomp 2.4.4 (which contains backported libseccomp commit 5696c89) or greater. In this case, to check if your host libseccomp is faccessat2-compatible, invoke scmp_sys_resolver faccessat2. If 439 is returned, faccessat2 is supported. If -1 is returned, faccessat2 is not supported. Note that if runc is older than v1.0.0-rc93, Docker must still be at least version 20.10.0, regardless of the result of this command.

**Comment by jmlagace** [comment]
I'm guessing then that having it documented here is all that can be expected. Hopefully, it will save time to whoever has a similar experience.

For completeness, what had me search for the cause was a Ruby on Rails application refusing to start with the application with the following error message:

```
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/bundle/ruby/3.0.0/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect'
/bundle/ruby/3.0.0/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
/bundle/ruby/3.0.0/gems/execjs-2.8.1/lib/execjs.rb:4:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
/bundle/ruby/3.0.0/gems/react-rails-2.6.1/lib/react/jsx.rb:1:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/bundle/ruby/3.0.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
/bundle/ruby/3.0.0/gems/react-rails-2.6.1/lib/react-rails.rb:2:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/gems/bundler-2.2.31/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/bundle/gems/bundler-2.2.31/lib/bundler/runtime.rb:55:in `each'
/bundle/gems/bundler-2.2.31/lib/bundler/runtime.rb:55:in `block in require'
/bundle/gems/bundler-2.2.31/lib/bundler/runtime.rb:44:in `each'
/bundle/gems/bundler-2.2.31/lib/bundler/runtime.rb:44:in `require'
/bundle/gems/bundler-2.2.31/lib/bundler.rb:175:in `require'
/usr/src/app/config/application.rb:25:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
/usr/src/app/Rakefile:4:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/bundle/ruby/3.0.0/gems/railties-6.0.4.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/bundle/ruby/3.0.0/gems/railties-6.0.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/bundle/ruby/3.0.0/gems/railties-6.0.4.1/lib/rails/command.rb:48:in `invoke'
/bundle/ruby/3.0.0/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in `<main>'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/ruby/3.0.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/src/app/bin/rails:9:in `<top (required)>'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/bundle/ruby/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/usr/src/app/bin/spring:15:in `require'
/usr/src/app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

The other symptom experienced was being unable to start IRB. It would give the following error:
```
/usr/local/lib/ruby/3.0.0/irb/locale.rb:121:in `load': No such file to load -- irb/error.rb (LoadError)
	from /usr/local/lib/ruby/3.0.0/irb/init.rb:195:in `init_error'
	from /usr/local/lib/ruby/3.0.0/irb/init.rb:18:in `setup'
	from /usr/local/lib/ruby/3.0.0/irb.rb:402:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /usr/local/bin/irb:23:in `load'
	from /usr/local/bin/irb:23:in `<main>'
```
