### ISSUE TITLE
Incompatible rubygems 2.6.2 and bundler < 1.12.0.rc on ruby:2.3.0-*

### ISSUE THREAD

**Issue by taoza** [docker-library/ruby#73]
See the closed issue on bundler: https://github.com/bundler/bundler/issues/4381. They had the compatibility issue fixed on 1.12.0.rc (through https://github.com/bundler/bundler/pull/4341) but the problem remain unsolved on [2.3.0-slim Dockerfile](https://github.com/docker-library/ruby/blob/c88f3a67da720bfa9fb1717960d90fd5db11c757/2.3/slim/Dockerfile) with the incompatible rubygems-2.6.2 and bundler-1.11.2.

How do we deal with this situation? Rollback rubygems to 2.6.1 or install bundler 1.12.0.rc?

**Comment by JeanMertz** [comment]
I'm also running into the same issue. Reverting to the `2.2` image for now.

**Comment by taoza** [comment]
I don't think everyone can revert back to 2.2 easily if they have started using some of the 2.3 features.

**Comment by JeanMertz** [comment]
Very true. And in fact, the `2.2` images where also updated, so they didn't work for me either.

I'm surprised that more people haven't ran into this issue yet.

The solution for me was to add the following to statements to the `Dockerfile` ineriting from `_/ruby`:

```dockerfile
RUN gem update --system 2.6.1
RUN gem install bundler --version $BUNDLER_VERSION
```

**Comment by javiercr** [comment]
Got the same problem :/

**Comment by chulkilee** [comment]
I hit this problem when using guard with my binstub (e.g. `/app/bin/guard), not global binstub (`/usr/local/bundle/bin/guard`). I guess guard is calling bundle exec, so it hit the same problem - bundle exec inside bundle exec.

It can be fixed by installing the same version of bundler inside docker, so I don't think this is a issue of rubygems/bundler.

See the following script with output. I don't know how it fixes the problem.

```sh
docker run -it ruby:2.3.1 /bin/bash

gem env
# RubyGems Environment:
#   - RUBYGEMS VERSION: 2.6.3
#   - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
#   - INSTALLATION DIRECTORY: /usr/local/bundle
#   - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
#   - RUBY EXECUTABLE: /usr/local/bin/ruby
#   - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
#   - SPEC CACHE DIRECTORY: /root/.gem/specs
#   - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
#   - RUBYGEMS PLATFORMS:
#     - ruby
#     - x86_64-linux
#   - GEM PATHS:
#      - /usr/local/bundle
#      - /root/.gem/ruby/2.3.0
#      - /usr/local/lib/ruby/gems/2.3.0
#   - GEM CONFIGURATION:
#      - :update_sources => true
#      - :verbose => true
#      - :backtrace => false
#      - :bulk_threshold => 1000
#      - "install" => "--no-document"
#      - "update" => "--no-document"
#   - REMOTE SOURCES:
#      - https://rubygems.org/
#   - SHELL PATH:
#      - /usr/local/bundle/bin
#      - /usr/local/sbin
#      - /usr/local/bin
#      - /usr/sbin
#      - /usr/bin
#      - /sbin
#      - /bin

bundle --version
# Bundler version 1.11.2

bundle config
# Settings are listed in order of priority. The top value will be used.
# silence_root_warning
# Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
# 
# app_config
# Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
# 
# bin
# Set via BUNDLE_BIN: "/usr/local/bundle/bin"
# 
# path
# Set via BUNDLE_PATH: "/usr/local/bundle"

cd /tmp
touch Gemfile
bundle install
# The Gemfile specifies no dependencies
# Resolving dependencies...
# Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
# Bundled gems are installed into /usr/local/bundle.

bundle config
# Settings are listed in order of priority. The top value will be used.
# disable_shared_gems
# Set for your local app (/usr/local/bundle/config): "1"
# 
# silence_root_warning
# Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
# 
# app_config
# Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
# 
# bin
# Set via BUNDLE_BIN: "/usr/local/bundle/bin"
# 
# path
# Set via BUNDLE_PATH: "/usr/local/bundle"

bundle exec bundle --version
# /usr/local/bin/bundle:22:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/gems/bundler-1.11.2/bin/bundle (LoadError)
#   from /usr/local/bin/bundle:22:in `<main>'

gem install bundler --version 1.11.2
# Fetching: bundler-1.11.2.gem (100%)
# Successfully installed bundler-1.11.2
# 1 gem installed

bundle config
# Settings are listed in order of priority. The top value will be used.
# disable_shared_gems
# Set for your local app (/usr/local/bundle/config): "1"
# 
# silence_root_warning
# Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
# 
# app_config
# Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
# 
# bin
# Set via BUNDLE_BIN: "/usr/local/bundle/bin"
# 
# path
# Set via BUNDLE_PATH: "/usr/local/bundle"

bundle exec bundle --version
# Bundler version 1.11.2
```

**Comment by morgoth** [comment]
Looks like bundler 1.12.0 landed in https://github.com/docker-library/ruby/commit/339c3257380212ef0cfdc5060f3c74bef41ab52b
Can this be closed?

**Comment by javiercr** [comment]
The new image hasn't been pushed to Docker Hub yet so I'm still getting the same error.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/1685

**Comment by javiercr** [comment]
With the latest version of the `ruby:2.2` image I'm getting the same problem:

```
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.12.3/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems.rb:278:in `activate_bin_path'
from /usr/local/bin/bundle:22:in `<main>'
```

**Comment by chulkilee** [comment]
I still see this problem

```
docker images ruby:2.3.1
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ruby                2.3.1               316ceaa79560        24 hours ago        729 MB
```

```sh
docker run -it ruby:2.3.1 /bin/bash -c 'bundle --version;touch Gemfile;bundle install;bundle exec bundle --version; gem install bundler; bundle exec bundle --version'
Bundler version 1.12.4
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into .usr/local/bundle.
bundler: failed to load command: bundle (/usr/local/bin/bundle)
Gem::Exception: can't find executable bundle
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.4/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
  /usr/local/bin/bundle:22:in `<top (required)>'
Fetching: bundler-1.12.4.gem (100%)
Successfully installed bundler-1.12.4
1 gem installed
Bundler version 1.12.4
```

**Comment by ayufan** [comment]
Me too on `ruby:2.1`.

**Comment by atipugin** [comment]
Same here, `ruby:2.3.1`.

**Comment by zeonglow** [comment]
unsubscribe

**Comment by Moghedrin** [comment]
Looks like this is a stale issue. I'm going to close it for now, but if it's still an issue, we can reopen.
