### ISSUE TITLE
Nested bundler is broken

### ISSUE THREAD

**Issue by johnl** [docker-library/ruby#82]
running bundler from within a bundler environment raises an exception. Tested in ruby:2.1 and ruby:2.3:
```
docker run -t -i ruby:2.3 bash
root@4e32ae9302e4:/# mkdir app
root@4e32ae9302e4:/# cd app
root@4e32ae9302e4:/app# echo "" > Gemfile
root@4e32ae9302e4:/app# bundle install
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into /usr/local/bundle.
root@4e32ae9302e4:/app# bundle exec bundle --version
bundler: failed to load command: bundle (/usr/local/bin/bundle)
Gem::Exception: can't find executable bundle
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path'
  /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
  /usr/local/bin/bundle:22:in `<top (required)>'
```

If I uninstall and reinstall the bundler gem, it fixes the problem:

```
root@4e32ae9302e4:/app# gem uninstall -i /usr/local/lib/ruby/gems/2.3.0 bundler
Remove executables:
	bundle, bundler

in addition to the gem? [Yn]  Y
Removing bundle
Removing bundler
Successfully uninstalled bundler-1.12.5
root@4e32ae9302e4:/app# gem install bundler
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
1 gem installed
root@4e32ae9302e4:/app# hash -r
root@4e32ae9302e4:/app# bundle exec bundle --version
Bundler version 1.12.5
```

This looks technically to be a bug in bundler (see work in https://github.com/bundler/bundler/issues/4602) but I think it's arising because bundler is installed in a non-standard way in these images. It's installed in /usr/local/lib/ruby/gems/2.3.0 by default during the image build, but *before* all the GEM_HOME gets configured. Once GEM_HOME is set, gems (and their binaries) go elsewhere.

https://github.com/docker-library/ruby/blob/master/2.3/Dockerfile#L43
https://github.com/docker-library/ruby/blob/master/2.3/Dockerfile#L47-L52

I'd suggest installing bundler after setting those environment variables, but it looks like it was specifically changed to be like that in https://github.com/docker-library/ruby/commit/9b1f77c11d663930f4175c683b1c5f268d4d8191 for some reason. Any thoughts?

**Comment by johnl** [comment]
Oh, for the record, nested bundler isn't just academic - in my case, it's broken parallel_tests, which runs multiple separate rspec tasks in parallel.
